services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: nexirift/suggestions
        working_dir: /app
        depends_on:
            db:
                condition: service_healthy
        ports:
            - '3000:3000'
        env_file: .env
    db:
        image: postgres:latest
        env_file: .env
        volumes:
            - db:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db:
